Changes to pgfree, kthread_end, and LTO support: |- Fixed pgfree assuming direct page mapping when adding page to freelist |- Replaced most assembly in kthread_end into C code |  |- Weird mix that might break with the wrong compilation flags |  |- As a result, implementation will probably be replaced by a reaper thread |- Fixed undefined reference to memset when compiling with LTO